- docs/pages.jl
- docs/src/tutorial.md
- src/parameter_indexing.jl
> docs: update `getp`, `setp` docstring, add tutorial

- .github/workflows/Downstream.yml
- docs/src/api.md
- docs/src/complete_sii.md
- src/SymbolicIndexingInterface.jl
- src/interface.jl
- src/parameter_indexing.jl
- src/state_indexing.jl
- src/symbol_cache.jl
- test/parameter_indexing_test.jl
- test/state_indexing_test.jl
> feat: add `IsTimeseriesTrait`, support timeseries objects in `getu`

- docs/src/simple_sii_sys.md
> docs: write `SymbolCache` tutorial

- docs/src/api.md
- docs/src/complete_sii.md
- src/SymbolicIndexingInterface.jl
- src/parameter_indexing_proxy.jl
- test/parameter_indexing_test.jl
> feat: add `ParameterIndexingProxy`

- src/parameter_indexing.jl
- src/state_indexing.jl
- test/parameter_indexing_test.jl
- test/state_indexing_test.jl
- also addresses type-stability of the closures returned from the above functions
> feat: improve getu/setu/getp/setp handling of nested variables

- docs/pages.jl
- src/SymbolicIndexingInterface.jl
- src/parameter_indexing.jl
- src/state_indexing.jl
- src/symbol_cache.jl
- test/parameter_indexing_test.jl
- test/state_indexing_test.jl
> refactor: make getp generic of the parameter container

- README.md
- docs/src/usage.md
- src/state_indexing.jl
> fix: do not call current_time for time-independent systems

- docs/src/api.md
- docs/src/complete_sii.md
- docs/src/usage.md
- src/SymbolicIndexingInterface.jl
- src/parameter_indexing.jl
- src/parameter_indexing_proxy.jl
- src/state_indexing.jl
- src/trait.jl
- test/parameter_indexing_test.jl
> feat: support indexing in mixed discrete-continuous systems

- src/state_indexing.jl
- test/parameter_indexing_test.jl
> fix: fix `getu` with parameter symbols

- Project.toml
- docs/src/api.md
- docs/src/complete_sii.md
- src/SymbolicIndexingInterface.jl
- src/interface.jl
- src/symbol_cache.jl
- src/trait.jl
- test/symbol_cache_test.jl
> feat: add `default_values` to interface

- src/trait.jl
Before:
```julia
julia> @be (expr, subs) symbolic_evaluate(_...)
Benchmark: 156 samples with 1 evaluation
min    453.542 μs (2318 allocs: 66.359 KiB)
median 501.958 μs (2318 allocs: 66.359 KiB)
mean   605.138 μs (2318 allocs: 66.359 KiB)
max    2.379 ms (2318 allocs: 66.359 KiB)
```
After:
```julia
julia> @be (expr, subs) symbolic_evaluate(_...)
Benchmark: 330 samples with 1 evaluation
min    269.209 μs (1183 allocs: 28.891 KiB)
median 274.625 μs (1183 allocs: 28.891 KiB)
mean   282.744 μs (1183 allocs: 28.891 KiB)
max    588.542 μs (1183 allocs: 28.891 KiB)
```
Add any other …
> refactor: improve `symbolic_evaluate` performance

- src/trait.jl
> docs: allow `symbolic_evaluate` to have arbitrary kwargs

- Project.toml
- docs/src/api.md
- docs/src/complete_sii.md
- docs/src/usage.md
- src/SymbolicIndexingInterface.jl
- src/remake.jl
- test/remake_test.jl
- test/runtests.jl
> feat: add `remake_buffer`

- docs/src/api.md
- docs/src/complete_sii.md
- src/parameter_indexing.jl
- test/parameter_indexing_test.jl
> feat: add `finalize_parameters_hook!`

- Project.toml
- src/SymbolicIndexingInterface.jl
- src/parameter_indexing.jl
- src/remake.jl
- src/trait.jl
- test/parameter_indexing_test.jl
- test/remake_test.jl
- test/trait_test.jl
> feat: support indexing Tuple parameters, add tests

- src/interface.jl
> fix: change `default_values` implementation for backward compatibility

- src/SymbolicIndexingInterface.jl
- src/parameter_indexing.jl
- src/state_indexing.jl
- src/value_provider_interface.jl
> refactor: return functors from getu and getp

- src/parameter_indexing.jl
- src/state_indexing.jl
> fix: add dedicated code paths for non-scalarized array symbolics in getu/getp

- Project.toml
- docs/make.jl
- docs/src/api.md
- docs/src/complete_sii.md
- docs/src/terminology.md
- src/SymbolicIndexingInterface.jl
- src/index_provider_interface.jl
- src/parameter_indexing.jl
- src/parameter_timeseries_collection.jl
- src/state_indexing.jl
- src/symbol_cache.jl
- src/trait.jl
- src/value_provider_interface.jl
- test/downstream/Project.toml
- test/example_test.jl
- test/parameter_indexing_test.jl
- test/parameter_timeseries_collection_test.jl
- test/runtests.jl
- test/simple_adjoints_test.jl
- test/state_indexing_test.jl
- test/symbol_cache_test.jl
> feat: add `is_parameter_timeseries` trait, improve parameter timeseries indexing

- src/parameter_indexing.jl
- src/state_indexing.jl
- test/parameter_indexing_test.jl
- test/state_indexing_test.jl
> fix: fix and test `getu` and `getp` with empty arrays

- Project.toml
- src/symbol_cache.jl
- test/symbol_cache_test.jl
> fix: default to ContinuousTimeseries for symbol not in `SymbolCache`

- src/parameter_indexing.jl
> fix: remove erroneous getter returned from setp

- docs/src/api.md
- src/index_provider_interface.jl
- src/symbol_cache.jl
> fix: fix stack overflow for methods using `symbolic_container` to define a fallback

- src/parameter_indexing.jl
- test/parameter_indexing_test.jl
> feat: allow calling parameter observed functions with parameter object

- docs/src/api.md
- src/SymbolicIndexingInterface.jl
- src/parameter_indexing.jl
- src/remake.jl
- test/downstream/Project.toml
- test/downstream/remake_arrayvars.jl
- test/parameter_indexing_test.jl
- test/remake_test.jl
- test/runtests.jl
> feat: add out-of-place `setp`, refactor `remake_buffer`

- src/remake.jl
- test/remake_test.jl
> fix: fix `remake_buffer` with a `Tuple` buffer and `Dict{Any, Any}` varmap

- docs/src/api.md
- src/SymbolicIndexingInterface.jl
- src/index_provider_interface.jl
- src/state_indexing.jl
- src/value_provider_interface.jl
- test/state_indexing_test.jl
> feat: support observed functions for history-dependent systems

- docs/src/api.md
- src/SymbolicIndexingInterface.jl
- src/batched_interface.jl
- test/batched_interface_test.jl
- test/downstream/batchedinterface_arrayvars.jl
> feat: add `setsym_oop` for `BatchedInterface`

- src/remake.jl
- test/remake_test.jl
For `InitializationProblem`s `state_values(prob)` can return `nothing`,
so calls like
```julia
remake_buffer(prob, state_values(prob), keys(u0), values(u0))
```
would lead to `StackOverflowError`s due to the fallback for the deprecated `Dict` method.
```julia
function remake_buffer(sys, oldbuffer, idxs, vals)
remake_buffer(sys, oldbuffer, Dict(idxs .=> vals))
end
```
This can crash julia if depwarns are enabled. The output would look like
```
julia> remake(prob1, u0=prob1.u0)
┌ Warning: `remake_buffer(sys, oldbuffer, vals::Dict)` is deprecated, use `remake_buffer(sys, oldbuffer, keys(vals), values(vals))` instead.
│   caller = remake_buffer(sys::NonlinearSystem, oldbuffer::Nothing, idxs::Vector{Int64}, vals::Vector{Any}) at remake.jl:59
└ @ SymbolicIndexingInterface …
```
> Fix possible `StackOverflowError`s for `remake_buffer` & `InitializationProblem`s

- docs/src/api.md
- docs/src/complete_sii.md
- docs/src/usage.md
- src/SymbolicIndexingInterface.jl
- src/batched_interface.jl
- src/parameter_indexing.jl
- src/problem_state.jl
- src/remake.jl
- src/state_indexing.jl
- src/value_provider_interface.jl
- test/batched_interface_test.jl
- test/downstream/batchedinterface_arrayvars.jl
- test/parameter_indexing_test.jl
- test/problem_state_test.jl
- test/simple_adjoints_test.jl
- test/state_indexing_test.jl
Rebased on top of #105 which should be merged first
> feat: add `setsym_oop`

- docs/src/api.md
- docs/src/complete_sii.md
- docs/src/usage.md
- src/SymbolicIndexingInterface.jl
- src/batched_interface.jl
- src/problem_state.jl
- src/remake.jl
- src/state_indexing.jl
- src/value_provider_interface.jl
- test/batched_interface_test.jl
- test/downstream/batchedinterface_arrayvars.jl
- test/parameter_indexing_test.jl
- test/problem_state_test.jl
- test/simple_adjoints_test.jl
- test/state_indexing_test.jl
> refactor: rename `getu`/`setu` to `getsym`/`setsym`

- src/index_provider_interface.jl
- src/parameter_indexing.jl
- src/state_indexing.jl
- test/state_indexing_test.jl
> feat: add support for directly generating tuple observed functions

- src/problem_state.jl
- test/problem_state_test.jl
- test/state_indexing_test.jl
Required to enable `remake` of DDEs/SDDEs.
> feat: add optional history function to `ProblemState`

- src/state_indexing.jl
- src/value_provider_interface.jl
- test/parameter_indexing_test.jl
- test/state_indexing_test.jl
> fix: handle cases for calling oop setter directly on state/parameter object

- src/remake.jl
- test/remake_test.jl
> fix: fix stack overflow on `remake_buffer` of `Dict`
